apiVersion: v2
name: sorry-cypress
description: A Helm chart for Sorry Cypress
type: application
version: 0.1.4
appVersion: 1.16.0
home: https://sorry-cypress.dev/
sources:
- https://github.com/sorry-cypress/sorry-cypress
icon: https://sorry-cypress.dev/public/octolumbercat.png
maintainers:
  - name: Tim Collins
    url: https://crumbhole.com
