name: Close inactive pull requests
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/stale@v5.0.0
        with:
          days-before-issue-stale: 60
          days-before-issue-close: 7
          days-before-pr-stale: 60
          days-before-pr-close: 7
          stale-pr-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 60 days with no activity. It will be closed if no further activity occurs."
          close-issue-message: "This issue was closed because it has been inactive for 7 days since being marked as stale."
          stale-pr-message: "This PR is stale because it has been open for 60 days with no activity. It will be closed if no further activity occurs."
          close-pr-message: "This PR was closed because it has been inactive for 7 days since being marked as stale."
          repo-token: ${{ secrets.CI_TOKEN }}
